# Generated by Django 6.0 on 2025-12-30 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('Diagnóstico', 'Diagnóstico'), ('Assessoria', 'Assessoria'), ('Recorrência', 'Recorrência'), ('Implementação', 'Implementação'), ('Club', 'Club')], max_length=50)),
                ('interlocutor_name', models.CharField(blank=True, max_length=255)),
                ('interlocutor_contact', models.CharField(blank=True, max_length=50)),
                ('interlocutor_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Concluído', 'Concluído'), ('Coleta de Dados', 'Coleta de Dados'), ('Atrasado', 'Atrasado'), ('Pausado', 'Pausado')], default='Em Andamento', max_length=50)),
                ('sla_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Atenção'), ('delay', 'Atrasado')], default='ok', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('delivery_model', models.CharField(blank=True, max_length=50)),
                ('financial_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.clientprofile')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('POP', 'POP'), ('Planilha', 'Planilha'), ('Contrato', 'Contrato'), ('Relatório', 'Relatório'), ('Diagnóstico', 'Diagnóstico')], max_length=50)),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('link', models.URLField(blank=True)),
                ('recording_link', models.URLField(blank=True)),
                ('attendees', models.TextField(help_text='Comma-separated list of attendees names')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('note_type', models.CharField(choices=[('internal', 'Interno'), ('external', 'Externo'), ('risk', 'Risco'), ('highlight', 'Destaque')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project')),
            ],
        ),
    ]
