# Generated by Django 6.0 on 2025-12-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('responsible_name', models.CharField(max_length=255)),
                ('responsible_phone', models.CharField(max_length=20)),
                ('owner_phone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('employee_count', models.IntegerField(default=0)),
                ('client_count', models.IntegerField(default=0)),
                ('has_mapped_processes', models.BooleanField(default=False)),
                ('is_reference', models.BooleanField(default=False)),
                ('software_accounting', models.CharField(blank=True, max_length=100)),
                ('software_note_capture', models.CharField(blank=True, max_length=100)),
                ('software_file_converter', models.CharField(blank=True, max_length=100)),
                ('software_whatsapp', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Churn', 'Churn')], default='Ativo', max_length=20)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
