# Generated by Django 6.0 on 2025-12-30 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ticket_type', models.CharField(max_length=100)),
                ('area', models.CharField(choices=[('Fiscal', 'Fiscal'), ('Contábil', 'Contábil'), ('Pessoal', 'Pessoal'), ('Domínio', 'Domínio'), ('Financeiro', 'Financeiro'), ('TI', 'TI'), ('Sucesso do Cliente', 'Sucesso do Cliente')], max_length=50)),
                ('priority', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], max_length=20)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em Análise', 'Em Análise'), ('Respondido Pelo Consultor', 'Respondido Pelo Consultor'), ('Respondido pelo Cliente', 'Respondido pelo Cliente'), ('Em Andamento', 'Em Andamento'), ('Aguardando Cliente', 'Aguardando Cliente'), ('Resolvido', 'Resolvido'), ('Concluído', 'Concluído')], default='Aberto', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_tickets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TicketInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('role', models.CharField(choices=[('client', 'Cliente'), ('support', 'Suporte'), ('system', 'Sistema')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='support.ticket')),
            ],
        ),
    ]
