# Generated by Django 6.0 on 2025-12-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_model', models.CharField(choices=[('fixed', 'Fixo'), ('hourly', 'Por Hora'), ('monthly', 'Mensal'), ('yearly', 'Anual')], max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Curso', 'Curso'), ('Diagnóstico', 'Diagnóstico'), ('Assessoria', 'Assessoria'), ('Horas', 'Horas'), ('Club', 'Club')], max_length=50)),
                ('payment_methods', models.CharField(help_text='Comma-separated payment methods', max_length=255)),
                ('onboarding_process', models.TextField(blank=True)),
                ('automation_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('meeting', 'Reunião'), ('task', 'Tarefa'), ('milestone', 'Marco')], max_length=20)),
                ('relative_days', models.IntegerField(default=0)),
                ('duration_hours', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='products.product')),
            ],
        ),
    ]
